### ISSUE TITLE
__main__ should be moved, according to poetry

### ISSUE THREAD

**Issue by asiniy** [devkarych/aioplate#8]
I get this when `__main__.py` is a root file, using poetry

```
/home/asiniy/.cache/pypoetry/virtualenvs/aioplate-jvuUMrzw-py3.10/bin/python: No module named app.__main__; 'app' is a package and cannot be directly executed
```

And this looks correct issue, my suggestion is to remove `__main__.py` to `app/` folder

**Comment by devkarych** [comment]
I decided to save only 1 option for environment setup. So, for beginners, version using pip & requirements is easier and I'l leave poetry from project.

**Comment by devkarych** [comment]
I moved `__main__.py` to `app/` folder and removed alternative way (pip) of environment setup. 
Thanks for submitted bug!
